config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments
  resources :tweets
  resources :users, only: %i[show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tweets#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet, counter_cache: :comments_count
  # Asocciations
  validates :body, presence: true, length: { maximum: 140 }
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  # Validations
  validates :body, presence: true, length: { maximum: 140 }
  # Associations
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar 

  # Validations
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :username, presence: true, uniqueness: true
  validates :name, presence: true

  # Associations
  has_many :tweets, dependent: :nullify
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: %i[index show]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name, :avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :name, :avatar])
  end

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action"
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit update destroy]

  # GET /comments
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  def show; end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit; end

  # POST /comments
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to tweet_path(@comment.tweet)
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to tweet_path(@comment.tweet)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to tweet_path(@comment.tweet)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:user_id, :tweet_id, :body)
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[show edit update destroy]

  # GET /tweets
  def index
    @tweets = Tweet.all.order(updated_at: :desc)
  end

  # GET /tweets/1
  def show; end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit; end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params)
    # @tweet_user = Tweet.find(params[:id]).user

    if @tweet.save
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /tweets/1
  def update
    if @tweet.update(tweet_params)
      redirect_to tweet_path(@tweet)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /tweets/1
  def destroy
    @tweet.destroy
    redirect_to tweets_url
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tweet
    @tweet = Tweet.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def tweet_params
    params.require(:tweet).permit(:body, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show]

  # GET /users/1
  def show; end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def avatar_for(user)
    avatar = user.avatar
    if avatar.empty?
      avatar_user = image_tag("avatar_default_user.png", alt: user.name)
    else
      avatar_user = image_tag(avatar.url, alt: user.name)
    end
    avatar_user
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def time_ago_in_words(from_time, include_seconds_or_options = {})
    distance_of_time_in_words(from_time, Time.zone.now, include_seconds_or_options)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_card.html.erb
<div class="grid bb">

  <%# Image %>
  <div>
    <% if comment.user.avatar.attached? %>
      <%= image_tag(comment.user.avatar, class: "image_circle_sm") %>
    <% else %>
      <%= image_tag("avatar_default_user1.png", class: "image_circle_sm") %>
    <% end %>
  </div>

  <%# Info container %>
  <div class="field flex input wrap text-left mb-4">
    <%# name username time %>
    <div>
    <%= link_to user_path(comment.user), class: "link" do%>
      <%= comment.user.name %>
      <span class="secondary-text">@<%= comment.user.username %></span>
      <span class="secondary-text"><%= time_ago_in_words(comment.updated_at) %></span>
    <%end%>
    </div>
    <%# Body %>
    <% if comment.is_a?(Comment) %>
      <%= link_to comment, class:"link text-left" do%>
        <%= comment.body %>
      <% end %>
    <% else %>
        <%= comment.body %>
    <% end %>
    <%# Comment counter %>
    <div class="flex justify-between">
      <div></div>
      <div class="flex gap-4">
        <%if current_user && current_user == comment.user %>
          <%#= link_to image_tag("destroy.png"), comment_path(comment),
          data: {turbo_method: :delete} %>
          <%= button_to "Destroy this comment", comment, method: :delete %>
          <%= link_to edit_comment_path(comment) do%>
            <%= image_tag("edit.png")%>
          <% end %>
        <% end %>
      </div>
    </div>
    

  </div>

</div>

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <strong>User:</strong>
    <%= comment.user_id %>
  </p>

  <p>
    <strong>Tweet:</strong>
    <%= comment.tweet_id %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= comment.body %>
  </p>

</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if current_user %>
    <div hidden>
      <%= form.label :user_id %>
      <%= form.text_field :user_id, value: current_user.id %>
    </div>
  <%end%>

  <% if current_user %> 
    <div hidden>
      <%= form.label :tweet_id, style: "display: block" %>
      <%= form.text_field :tweet_id, value: tweet.id %>
    </div>
  <%end%>

  <div class="grid">
    <% if current_user.avatar.attached? %>
      <%= image_tag(current_user.avatar, class: "image_circle_sm") %>
    <%end%>
    <div class="input ">
      <div class="field flex mb-4">
        <%= form.text_area :body,
        placeholder: "Remember to thing before write...",
          class: "input__container select__input border-none" %>
      </div>

      <div class="actions flex flex-column wrap items-right">
        <%= form.submit "Comment", class: "button button--primary "  %>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<section class="section-md">
  <div class="container flex flex-column wrap text-center items-center mb-4 bg-white">
    <h1>Edit comment</h1>
    <div class="input">
    <%= form_with(model: @comment) do |form| %>
      </div>
        <% if @comment.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

            <ul>
              <% @comment.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <% if current_user %>
          <div hidden>
            <%= form.label :user_id %>
            <%= form.text_field :user_id, value: current_user.id %>
          </div>
        <%end%>

        <% if current_user %> 
          <div hidden>
            <%= form.label :tweet_id, style: "display: block" %>
            <%= form.text_field :tweet_id, value: @comment.tweet.id %>
          </div>
        <%end%>

        <div class="grid">
          <% if current_user.avatar.attached? %>
            <%= image_tag(current_user.avatar, class: "image_circle_sm") %>
          <%end%>
          <div class="input ">
            <div class="field flex mb-4">
              <%= form.text_area :body,
              placeholder: "Remember to thing before write...",
                class: "input__container select__input border-none" %>
            </div>

            <div class="actions flex flex-column wrap items-right">
              <%= form.submit "Comment", class: "button button--primary "  %>
            </div>
          </div>
        </div>
      <% end %>

      <br>

  </div>
</section>
  

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

app/views/layouts/_footer.html.erb
<footer class="footer_content">
      <div>
      <p>© 2021 - Codeable Tweetable</p>
      <p>Build with ♥ by</p>
      <div class="footer_content2"> 
        <div>
            <div class="container__svg">
              <svg><use xlink:href="#in"></svg>
            </div>
            <p>Fabio Fiestas</p>
        </div>  

      </div>
    </footer>

    <div hidden>
      <svg xmlns="http://www.w3.org/2000/svg">
        <symbol id="in" width="20" height="20" viewBox="0 0 18 18">
          <path d="M0.666667 0H11.3333C11.5101 0 11.6797 0.0702379 11.8047 0.195262C11.9298 0.320286 12 0.489856 12 0.666667V11.3333C12 11.5101 11.9298 11.6797 11.8047 11.8047C11.6797 11.9298 11.5101 12 11.3333 12H0.666667C0.489856 12 0.320286 11.9298 0.195262 11.8047C0.0702379 11.6797 0 11.5101 0 11.3333V0.666667C0 0.489856 0.0702379 0.320286 0.195262 0.195262C0.320286 0.0702379 0.489856 0 0.666667 0ZM1.33333 1.33333V10.6667H10.6667V1.33333H1.33333ZM3 4C2.73478 4 2.48043 3.89464 2.29289 3.70711C2.10536 3.51957 2 3.26522 2 3C2 2.73478 2.10536 2.48043 2.29289 2.29289C2.48043 2.10536 2.73478 2 3 2C3.26522 2 3.51957 2.10536 3.70711 2.29289C3.89464 2.48043 4 2.73478 4 3C4 3.26522 3.89464 3.51957 3.70711 3.70711C3.51957 3.89464 3.26522 4 3 4ZM2.33333 4.66667H3.66667V9.66667H2.33333V4.66667ZM6 4.95333C6.38933 4.57667 6.844 4.33333 7.33333 4.33333C8.714 4.33333 9.66667 5.45267 9.66667 6.83333V9.66667H8.33333V6.83333C8.33333 6.52391 8.21042 6.22717 7.99162 6.00838C7.77283 5.78958 7.47609 5.66667 7.16667 5.66667C6.85725 5.66667 6.5605 5.78958 6.34171 6.00838C6.12292 6.22717 6 6.52391 6 6.83333V9.66667H4.66667V4.66667H6V4.95333Z" fill="#303036"/>
        </symbol>
      </svg>
    </div>

app/views/layouts/_header.html.erb
<header>
  <div class="container-lg">
    <nav class="nav__tweet">
      <%= link_to root_path, class:"text-decoration-none" do %>
        <span class="title">Tweet</span>
      <% end %>
      <input type="checkbox" id="menu-mobile" >
      <label for="menu-mobile" id="toogle-close"  >
        <i class="ri-close-line "></i>
      </label>
      <label for="menu-mobile" id="toogle-open" >
        <i class="ri-menu-line"></i>
      </label>
      <!-- <label for="menu-mobile" id="toogle-open">a</label> -->
      <ul class="nav--links expandable">
        <li>
        <% if current_user%>
          <p><%=current_user.username%> </p>
        <% end %>
        </li>
        <li><%= link_to "Tweets", root_path, class: "link text-sm" %>
      <% if current_user %>
        <li><%=link_to "Profile", user_path(current_user), class:"link text-sm" %></li>
        <li><%=button_to "Log Out", destroy_user_session_path, :method=> :delete, class:"button button--secondary button--sm" %></li>
      <% else %>
        <li><%=button_to "Log In", new_user_session_path, :method => :get, class:"button button--primary button--sm" %></li>
      <% end %>  
      </ul>
    </nav>
  </div>

</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TweetableIndividual</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render "layouts/header" %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
       
    <%= yield %>

    <%= render "layouts/footer" %>
  </body>
</html>

app/views/tweets/_card.html.erb
<div class="grid bb">

  <%# Image %>
  <div>
    <% if tweet.user.avatar.attached? %>
      <%= image_tag(tweet.user.avatar, class: "image_circle_sm") %>
    <% else %>
      <%= image_tag("avatar_default_user1.png", class: "image_circle_sm") %>
    <% end %>
  </div>

  <%# Info container %>
  <div class="field flex input wrap text-left mb-4">
    <%# name username time %>
    <div>
    <%= link_to user_path(tweet.user), class: "link" do%>
      <%= tweet.user.name %>
      <span class="secondary-text">@<%= tweet.user.username %></span>
      <span class="secondary-text"><%= time_ago_in_words(tweet.updated_at) %></span>
    <%end%>
    </div>
    <%# Body %>
    <% if tweet.is_a?(Tweet) %>
      <%= link_to tweet, class:"link text-left" do%>
        <%= tweet.body %>
      <% end %>
    <% else %>
        <%= tweet.body %>
    <% end %>
    <%# Comment counter %>
    <div class="flex justify-between">
      <% if tweet.is_a?(Tweet) %>
        <div class="flex">
          <% if current_user %>
            <%= link_to tweet do%>
              <%= image_tag("comment.png")%>
            <% end %>
          <% else %>
              <%= image_tag("comment.png")%>
          <% end %>
          <span class="ml-1"><%= tweet.comments_count %></span>
        </div>
      <% end %>
      <div class="flex gap-4">
        <%if current_user && current_user == tweet.user %>
        <%= link_to image_tag("destroy.png"), tweet_path(tweet),
        data: {turbo_method: :delete} %>

          <%= link_to edit_tweet_path(tweet) do%>
            <%= image_tag("edit.png")%>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <% if current_user %>
    <div hidden>
      <%= form.label :user_id %>
      <%= form.text_field :user_id, value: current_user.id %>
    </div>
  <%end%>

  <div class="grid">
    <% if current_user.avatar.attached? %>
      <%= image_tag(current_user.avatar, class: "image_circle_sm") %>
    <% else %>
      <%= image_tag("avatar_default_user1.png", class: "image_circle_sm") %>
    <%end%>
    <div class="input ">
      <div class="field flex mb-4">
        <%= form.text_area :body,
        placeholder: "Remember to thing before write...",
          class: "input__container select__input border-none" %>
      </div>

      <div class="actions flex flex-column wrap items-right">
        <%= form.submit "Tweet", class: "button button--primary "  %>
      </div>
    </div>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Body:</strong>
    <%= tweet.body %>
  </p>

  <p>
    <strong>Comments count:</strong>
    <%= tweet.comments_count %>
  </p>

  <p>
    <strong>User:</strong>
    <%= tweet.user_id %>
  </p>

</div>

app/views/tweets/edit.html.erb
<section class="section-md">
  <div class="container flex flex-column wrap text-center items-center mb-4 bg-white">
    <h1 class="">Edit tweet</h1>

    <%= form_with(model: @tweet) do |form| %>
      <% if @tweet.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

          <ul>
            <% @tweet.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      
      <% if current_user %>
        <div hidden>
          <%= form.label :user_id %>
          <%= form.text_field :user_id, value: current_user.id %>
        </div>
      <%end%>

      <div class="grid">
        <% if current_user.avatar.attached? %>
          <%= image_tag(current_user.avatar, class: "image_circle_sm") %>
        <%end%>
        <div class="input ">
          <div class="field flex mb-4">
            <%= form.text_area :body,
            placeholder: "Remember to thing before write...",
              class: "input__container select__input border-none" %>
          </div>

          <div class="actions flex flex-column wrap items-right">
            <%= form.submit "Tweet", class: "button button--primary "  %>
          </div>
        </div>
      </div>
    <% end %>


    <br>

    <div>
      <%= link_to "Show this tweet", @tweet %> |
      <%= link_to "Back to tweets", tweets_path %>
    </div>
  </div>
</section>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<section class="section-md">
  <div class="container flex flex-column wrap text-center items-center mb-4 bg-white">
    <h1 class="content-lg">Home</h1><br />
    <% if current_user %>
      <div class="input bb">
        <%= render "tweets/form", {tweet: Tweet.new} %><br />
      </div>
      <br />
    <% end %>
    <div id="tweets">
      <% @tweets.each do |tweet| %>
        <%= render "card", tweet: tweet %>
        <br />
      <% end %>
    </div>

    <%= link_to "New tweet", new_tweet_path %>
  </div>
</section>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%#= render @tweet %>
<section class="section-md">
  <div class="container flex flex-column wrap text-center items-center mb-4 bg-white">
  
    <div id="tweets", class="input">
      <%= render "card", tweet: @tweet %><br/>
    </div>


    <% if current_user %>
      <div class="input bb">
        <%= render "comments/form", {comment: Comment.new, tweet: @tweet} %><br />
      </div>
      <br />
    <% end %>

    <% @tweet.comments.each do |comment| %>
      <div id="tweets", class="input">
        <%= render "comments/card", comment: comment %>
      </div>
      <hr>
    <% end %>

  </div>
</section>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_user.html.erb
 <%# User profile %>

<div id="<%= dom_id user %>" class="flex flex-column items-center">

  <h1 class=" heading--sm mb-4">Profile</h1>
  <% if user.avatar.attached? %>
    <%= image_tag(user.avatar, class: "image_circle_lg mb-4") %>
  <% else %>
    <%= image_tag("avatar_default_user1.png", class: "image_circle_sm mb-4") %>
  <% end %>
  
  <div class="flex flex-column text-center ">
    <span class="mb-4"><%= user.name %></span>
    <span class="mb-4">@<%= user.username %></span>
    <span class="mb-4">Joined on <%= user.created_at.strftime('%d, %Y') %></span>
  </div>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>

<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<section class="section-md">
  <div class="container flex flex-column wrap text-center items-center mb-4 bg-white">

    <div class="flex flex-column wrap text-center items-center mb-4">
      <%= render @user %>
      <%# Add polices: to view button edit profile %>

      <% if current_user == @user%>
        <%=button_to "Edit Profile", edit_user_registration_path(@user), method: :get, class: "button button--primary mb-4" %>
      <% end %>
      <%# end polices %>

    </div>

    <div>
      <h2 class="mb-4 text-center">Tweets</h2>
      <% @user.tweets.each do |tweet| %>
        <%= render "/tweets/card", tweet: tweet%> 
      <% end %>
    </div>

  </div>
</section>

  <div hidden>
    <div>
      <svg><use xlink:href="#destroy"></svg>
      <svg><use xlink:href="#edit"></svg>
    </div>
    <div>
      <svg><use xlink:href="#comment"></svg>
      <svg><use xlink:href="#like"></svg>
    </div> 
  </div>
  <div hidden>
    <svg  xmlns="http://www.w3.org/2000/svg" >
      <symbol id = "destroy" viewBox="0 0 18 20">
        <path d="M16 5L15.1327 17.1425C15.0579 18.1891 14.187 19 13.1378 19H4.86224C3.81296 19 2.94208 18.1891 2.86732 17.1425L2 5M7 9V15M11 9V15M12 5V2C12 1.44772 11.5523 1 11 1H7C6.44772 1 6 1.44772 6 2V5M1 5H17" stroke="#7A7A7A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
       </symbol>
    </svg>

    <svg  xmlns="http://www.w3.org/2000/svg" >
      <symbol id = "edit" viewBox="0 0 19 19">
        <path d="M8 3H3C1.89543 3 1 3.89543 1 5V16C1 17.1046 1.89543 18 3 18H14C15.1046 18 16 17.1046 16 16V11M14.5858 1.58579C15.3668 0.804738 16.6332 0.804738 17.4142 1.58579C18.1953 2.36683 18.1953 3.63316 17.4142 4.41421L8.82842 13H6L6 10.1716L14.5858 1.58579Z" stroke="#7A7A7A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
       </symbol>
    </svg>

    <svg  xmlns="http://www.w3.org/2000/svg" >
      <symbol id = "comment" viewBox="0 0 20 18">
      <path d="M6 9H6.01M10 9H10.01M14 9H14.01M19 9C19 13.4183 14.9706 17 10 17C8.46073 17 7.01172 16.6565 5.74467 16.0511L1 17L2.39499 13.28C1.51156 12.0423 1 10.5743 1 9C1 4.58172 5.02944 1 10 1C14.9706 1 19 4.58172 19 9Z" stroke="#7A7A7A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
       </symbol>
    </svg>

    <svg  xmlns="http://www.w3.org/2000/svg" >
      <symbol id = "like" viewBox="0 0 20 18">
        <path d="M2.31802 2.31802C0.56066 4.07538 0.56066 6.92462 2.31802 8.68198L10.0001 16.364L17.682 8.68198C19.4393 6.92462 19.4393 4.07538 17.682 2.31802C15.9246 0.56066 13.0754 0.56066 11.318 2.31802L10.0001 3.63609L8.68198 2.31802C6.92462 0.56066 4.07538 0.56066 2.31802 2.31802Z" stroke="#7A7A7A" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/>
       </symbol>
    </svg>
  </div>